import "./globals.css";
// import { headers } from "next/headers";
import { ToastProvider } from "@/contexts/ToastContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // const headerList = await headers()
  // const currentPath = headerList.get("x-current-path")
  // console.log('currentPath', currentPath)
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ToastProvider>
          {children}
        </ToastProvider>
      </body>
    </html>
  )
}
